spring:
  application:
    name: sso-authserver
  database:
    url: jdbc:mysql://localhost:3306/auth?useUnincode=true&characterSet=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //
#  redis:
#    host:
#    port:
#    password:
#
#
server:
  port: 9092


