spring:
  cloud:
    # 开启服务网关的注册、发现机制
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由配置（规则由ID、目标URL、一组predicates及一组filters构成)
      routes:
        - id: sso-resourceserver
          # lb代表从注册中心获取服务，格式为lb://$(注册服务的名字）
          uri: lb://sso-resourceserver
          predicates:
            # 通过路径进行匹配
            - Path=/resources/**
          filters:
            - StripPrefix=1