spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    spearator: //

  # Redis服务地址
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456

mybatis-plus:
  mapper-localtions: classpath:mybatis/*.xml
  typeAliasesPackage: com.ornn.wallet.entity
  global-config:
    db-config:
      # 主键策略
      id-type: auto
      # 字段策略
      field-strategy: not_empty
      # 进行驼峰与下划线转换
      column-underline: true
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: postgresql
    refresh: false
  configuration:
    # 下划字段转换驼峰命名
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
