spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/payment
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    spearator: //

  # Redis?????
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

mybatis-plus:
  mapper-localtions: classpath:mybatis/*.xml
  typeAliasesPackage: com.ornn.wallet.entity
  global-config:
    db-config:
      # ????
      id-type: auto
      # ????
      field-strategy: not_empty
      # ????????????Java?????????? ?? ? ??? ?????
      column-underline: true
      # ??????
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: postgresql
    refresh: false
  configuration:
    # ??????????? ????????? ??? ??????????
    map-underscore-to-camel-case: true
    cache-enabled: false
    # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
