spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource?useUnincode=true&characterSet=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //
mybatis-plus:
  mapper-default-scope: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
security:
  oauth2:
    checkTokenUrl: http://localhost:9092/oauth/check_token
    clientId: resourceClient
    clientSecret: 123456
